language: ruby
cache: bundler

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rails webpacker:compile

script:
 - bundle exec rspec spec
 - bundle exec cucumber

branches:
  only:
  - master
