language: ruby
cache: bundler

services:
  - postgresql

before_install:
  - nvm install --lts

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn
  - bundle exec rails db:create db:migrate

script:
 - bundle exec rspec spec
 - bundle exec cucumber

branches:
  only:
  - master
